// <auto-generated />
namespace Our_Ecommerce_store_GIS_40.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_order_detail_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_order_detail_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202003152054434_update_order_detail_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
